# Generated by Django 5.0.3 on 2024-03-28 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=35, verbose_name="Название")),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="content/%Y/%m", verbose_name="Фото"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="О товаре")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "volume",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Кол-во"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Hoodies_and_sweatshirtsClothingProduct",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="product.product",
                    ),
                ),
                (
                    "care_instructions",
                    models.CharField(
                        choices=[("hand_wash", "Только ручная стирка")],
                        default="hand_wash",
                        max_length=20,
                        verbose_name="Уход",
                    ),
                ),
                ("size", models.CharField(max_length=10, verbose_name="Размер")),
                (
                    "зелённый/бежевый",
                    models.CharField(max_length=20, verbose_name="Цвет"),
                ),
                (
                    "the_length_of_the_sleeve",
                    models.CharField(max_length=20, verbose_name="Длина рукава"),
                ),
                ("hood", models.CharField(max_length=10, verbose_name="Капюшон")),
                ("style", models.CharField(max_length=40, verbose_name="Стиль")),
                ("silhouette", models.CharField(max_length=40, verbose_name="Силуэт")),
                ("compound", models.CharField(max_length=40, verbose_name="Состав")),
                ("drawing", models.CharField(max_length=40, verbose_name="Рисунок")),
                (
                    "clothing_collection",
                    models.CharField(max_length=35, verbose_name="Коллекция"),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("product.product", models.Model),
        ),
        migrations.CreateModel(
            name="JeansClothingProduct",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="product.product",
                    ),
                ),
                (
                    "care_instructions",
                    models.CharField(
                        choices=[("hand_wash", "Только ручная стирка")],
                        default="hand_wash",
                        max_length=20,
                        verbose_name="Уход",
                    ),
                ),
                ("size", models.CharField(max_length=10, verbose_name="Размер")),
                (
                    "зелённый/бежевый",
                    models.CharField(max_length=20, verbose_name="Цвет"),
                ),
                (
                    "lining_material",
                    models.CharField(max_length=40, verbose_name="Материал подкладки"),
                ),
                ("silhouette", models.CharField(max_length=40, verbose_name="Силуэт")),
                ("fashion", models.CharField(max_length=40, verbose_name="Фасон")),
                ("style", models.CharField(max_length=40, verbose_name="Стиль")),
                ("compound", models.CharField(max_length=40, verbose_name="Состав")),
                (
                    "clothing_collection",
                    models.CharField(max_length=35, verbose_name="Коллекция"),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("product.product", models.Model),
        ),
        migrations.CreateModel(
            name="OuterwearClothingProduct",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="product.product",
                    ),
                ),
                (
                    "care_instructions",
                    models.CharField(
                        choices=[("hand_wash", "Только ручная стирка")],
                        default="hand_wash",
                        max_length=20,
                        verbose_name="Уход",
                    ),
                ),
                ("size", models.CharField(max_length=10, verbose_name="Размер")),
                (
                    "зелённый/бежевый",
                    models.CharField(max_length=20, verbose_name="Цвет"),
                ),
                ("hood", models.CharField(max_length=10, verbose_name="Капюшон")),
                ("silhouette", models.CharField(max_length=40, verbose_name="Силуэт")),
                ("compound", models.CharField(max_length=40, verbose_name="Состав")),
                (
                    "lining_composition",
                    models.CharField(max_length=40, verbose_name="Состав подкладки"),
                ),
                (
                    "insulation_composition",
                    models.CharField(max_length=45, verbose_name="Состав утеплителя"),
                ),
                (
                    "upper_composition",
                    models.CharField(max_length=45, verbose_name="Состав верха"),
                ),
                (
                    "clothing_collection",
                    models.CharField(max_length=35, verbose_name="Коллекция"),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("product.product", models.Model),
        ),
        migrations.CreateModel(
            name="ShirtsClothingProduct",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="product.product",
                    ),
                ),
                (
                    "care_instructions",
                    models.CharField(
                        choices=[("hand_wash", "Только ручная стирка")],
                        default="hand_wash",
                        max_length=20,
                        verbose_name="Уход",
                    ),
                ),
                ("size", models.CharField(max_length=10, verbose_name="Размер")),
                (
                    "зелённый/бежевый",
                    models.CharField(max_length=20, verbose_name="Цвет"),
                ),
                ("silhouette", models.CharField(max_length=40, verbose_name="Силуэт")),
                ("compound", models.CharField(max_length=40, verbose_name="Состав")),
                (
                    "the_length_of_the_sleeve",
                    models.CharField(max_length=20, verbose_name="Длина рукава"),
                ),
                ("hood", models.CharField(max_length=10, verbose_name="Капюшон")),
                ("style", models.CharField(max_length=40, verbose_name="Стиль")),
                ("drawing", models.CharField(max_length=40, verbose_name="Рисунок")),
                (
                    "clothing_collection",
                    models.CharField(max_length=35, verbose_name="Коллекция"),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("product.product", models.Model),
        ),
        migrations.CreateModel(
            name="ShortsClothingProduct",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="product.product",
                    ),
                ),
                (
                    "care_instructions",
                    models.CharField(
                        choices=[("hand_wash", "Только ручная стирка")],
                        default="hand_wash",
                        max_length=20,
                        verbose_name="Уход",
                    ),
                ),
                ("size", models.CharField(max_length=10, verbose_name="Размер")),
                (
                    "зелённый/бежевый",
                    models.CharField(max_length=20, verbose_name="Цвет"),
                ),
                ("style", models.CharField(max_length=40, verbose_name="Стиль")),
                ("fashion", models.CharField(max_length=40, verbose_name="Фасон")),
                ("silhouette", models.CharField(max_length=40, verbose_name="Силуэт")),
                ("compound", models.CharField(max_length=60, verbose_name="Состав")),
                (
                    "fit_type",
                    models.CharField(max_length=35, verbose_name="Тип посадки"),
                ),
                ("drawing", models.CharField(max_length=40, verbose_name="Рисунок")),
                (
                    "clothing_collection",
                    models.CharField(max_length=35, verbose_name="Коллекция"),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("product.product", models.Model),
        ),
        migrations.CreateModel(
            name="SportClothingProduct",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="product.product",
                    ),
                ),
                (
                    "care_instructions",
                    models.CharField(
                        choices=[("hand_wash", "Только ручная стирка")],
                        default="hand_wash",
                        max_length=20,
                        verbose_name="Уход",
                    ),
                ),
                ("size", models.CharField(max_length=10, verbose_name="Размер")),
                (
                    "зелённый/бежевый",
                    models.CharField(max_length=20, verbose_name="Цвет"),
                ),
                ("fashion", models.CharField(max_length=40, verbose_name="Фасон")),
                ("silhouette", models.CharField(max_length=40, verbose_name="Силуэт")),
                ("compound", models.CharField(max_length=40, verbose_name="Состав")),
                ("style", models.CharField(max_length=40, verbose_name="Стиль")),
                (
                    "fit_type",
                    models.CharField(max_length=35, verbose_name="Тип посадки"),
                ),
                ("drawing", models.CharField(max_length=40, verbose_name="Рисунок")),
                (
                    "clothing_collection",
                    models.CharField(max_length=35, verbose_name="Коллекция"),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("product.product", models.Model),
        ),
        migrations.CreateModel(
            name="TrousersClothingProduct",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="product.product",
                    ),
                ),
                (
                    "care_instructions",
                    models.CharField(
                        choices=[("hand_wash", "Только ручная стирка")],
                        default="hand_wash",
                        max_length=20,
                        verbose_name="Уход",
                    ),
                ),
                ("size", models.CharField(max_length=10, verbose_name="Размер")),
                (
                    "зелённый/бежевый",
                    models.CharField(max_length=20, verbose_name="Цвет"),
                ),
                (
                    "length_trousers",
                    models.CharField(max_length=20, verbose_name="Длина брюк"),
                ),
                (
                    "lining_material",
                    models.CharField(max_length=40, verbose_name="Материал подкладки"),
                ),
                (
                    "waist_height",
                    models.CharField(max_length=35, verbose_name="Высота талии"),
                ),
                ("fashion", models.CharField(max_length=40, verbose_name="Фасон")),
                ("silhouette", models.CharField(max_length=40, verbose_name="Силуэт")),
                ("compound", models.CharField(max_length=40, verbose_name="Состав")),
                ("style", models.CharField(max_length=40, verbose_name="Стиль")),
                ("drawing", models.CharField(max_length=40, verbose_name="Рисунок")),
                (
                    "clothing_collection",
                    models.CharField(max_length=35, verbose_name="Коллекция"),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("product.product", models.Model),
        ),
        migrations.CreateModel(
            name="Tshirts_and_longsleevesClothingProduct",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="product.product",
                    ),
                ),
                (
                    "care_instructions",
                    models.CharField(
                        choices=[("hand_wash", "Только ручная стирка")],
                        default="hand_wash",
                        max_length=20,
                        verbose_name="Уход",
                    ),
                ),
                ("size", models.CharField(max_length=10, verbose_name="Размер")),
                (
                    "зелённый/бежевый",
                    models.CharField(max_length=20, verbose_name="Цвет"),
                ),
                ("style", models.CharField(max_length=40, verbose_name="Стиль")),
                ("silhouette", models.CharField(max_length=40, verbose_name="Силуэт")),
                (
                    "the_length_of_the_sleeve",
                    models.CharField(max_length=20, verbose_name="Длина рукава"),
                ),
                ("drawing", models.CharField(max_length=40, verbose_name="Рисунок")),
                ("compound", models.CharField(max_length=40, verbose_name="Состав")),
                (
                    "clothing_collection",
                    models.CharField(max_length=35, verbose_name="Коллекция"),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("product.product", models.Model),
        ),
    ]
