# Generated by Django 5.0.3 on 2024-03-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Face",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=35, verbose_name="Название")),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="content/%Y/%m", verbose_name="Фото"
                    ),
                ),
            ],
        ),
    ]
